--DROP TABLE IF EXISTS W4_USER;

/* 사용자 테이블 생성 */
CREATE TABLE IF NOT EXISTS W4_USER
  (
     USER_ID    VARCHAR(30) NOT NULL PRIMARY KEY
     , SYSTEM   VARCHAR(5) NOT NULL
     , EMAIL    VARCHAR(50) NOT NULL
     , PASSWORD VARCHAR(20) NOT NULL
     , REG_USER VARCHAR(20) NOT NULL
     , REG_DT   DATE NOT NULL
     , UPT_USER VARCHAR(20) NOT NULL
     , UPT_DT   DATE NOT NULL
  ); 