DROP TABLE IF EXISTS W4_MENU;

/* 메뉴 테이블 생성 */
CREATE TABLE IF NOT EXISTS W4_MENU
  (
     MENU_ID    VARCHAR(22) PRIMARY KEY
     , MENU_NM  VARCHAR(50) NOT NULL
     , GRP      INT NOT NULL
     , SEQ      INT NOT NULL
     , LEVEL    INT NOT NULL
     , PARENT   VARCHAR(22)
     , URL      VARCHAR(20)
     , USE_YN   CHAR(1) NOT NULL
     , REG_USER VARCHAR(20) NOT NULL
     , REG_DT   DATE NOT NULL
     , UPT_USER VARCHAR(20) NOT NULL
     , UPT_DT   DATE NOT NULL
  );
  
  CREATE SEQUENCE W4_MENU_SEQ;
  
  DROP SEQUENCE W4_MENU_SEQ;
  
  SELECT W4_MENU_SEQ FROM dual;
  
  SELECT NEXTVAL FOR W4_MENU_SEQ FROM dual;