DROP TABLE W4_USER;
CREATE TABLE W4_USER
  (
     USER_ID    VARCHAR(22) NOT NULL PRIMARY KEY
     , SYSTEM   VARCHAR(5) NOT NULL
     , EMAIL    VARCHAR(20) NOT NULL
     , PASSWORK VARCHAR(20) NOT NULL
     , REG_DT   DATE NOT NULL
     , UPT_DT   DATE NOT NULL
  ); 